apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: jenkins
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"