apiVersion: v1
kind: Service
metadata:
  name: mydeployment #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: mydeployment
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 80 #The port for the React.js application container
