

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-hello-world
  namespace: jenkins
spec:
  stripPrefix:
    prefixes:
      - /hello-world

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello-world
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`xdork.duckdns.org`) && PathPrefix(`/hello-world/`)"
      services:
        - kind: Service
          name: hello-world
          port: 80
      middlewares:
      - name: stripprefix-hello-world
